---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-httpd-config
  namespace: testing
data:
  apache.vhost.conf: |
    # Set the ServerName to localhost
    ServerName localhost

    # Configure a VirtualHost to handle requests on port 80
    <VirtualHost *:80>
        # Proxy PHP requests to port 9000 PHP-FPM container
        ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php-fpm:9000/app/public/$1
        
        # Set the DocumentRoot for the virtual host
        DocumentRoot /app/public/
        
        # Directory configuration for the DocumentRoot
        <Directory /app/public>
            AllowOverride None
            Require all granted
            FallbackResource /index.php
        </Directory>   

        # Define the CustomLog and ErrorLog destinations
        CustomLog /proc/self/fd/1 common
        ErrorLog /proc/self/fd/2
    </VirtualHost>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-server
  namespace: testing
  labels:
    app: httpd-server
    layer: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-server
  template:
    metadata:
      labels:
        app: httpd-server
    spec:
      containers:
        - name: httpd-server
          image: public.ecr.aws/o6a6b5p9/application:httpd-v1
          ports:
            - containerPort: 80
          volumeMounts:
          - name: apache-httpd-config-volume
            mountPath: /usr/local/apache2/conf/extra
      volumes:
      - name: apache-httpd-config-volume
        configMap:
          name: apache-httpd-config

---
kind: Service 
apiVersion: v1 
metadata:
  name: httpd-server
  namespace: testing
  labels:
    app: httpd-server
    layer: backend
spec:
  type: ClusterIP
  selector:
    app: httpd-server
  ports:
    - port: 80
      targetPort: 80
