---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-fpm-config
  namespace: testing
data:
  www.conf: |
    ; /etc/php/7.4/fpm/pool.d/www.conf

    ; a pool called www
    [symfony]
    user = www-data
    group = www-data

    ; use a unix domain socket
    ; listen = /var/run/php/php7.4-fpm.sock

    ; or listen on a TCP connection
    listen = 0.0.0.0:9000
    chdir = /app/public

    pm = static
    pm.max_children = 20

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: testing
  labels:
    app: php-fpm
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm 
    spec:
      containers:
        - name: php-fpm
          image: public.ecr.aws/o6a6b5p9/application:php-fpm-v2
          ports:
            - containerPort: 9000
          volumeMounts:
          - name: php-fpm-config-volume
            mountPath: /etc/php/8.2/fpm/pool.d
      volumes:
      - name: php-fpm-config-volume
        configMap:
          name: php-fpm-config

---
kind: Service 
apiVersion: v1 
metadata:
  name: php-fpm
  namespace: testing
  labels:
    app: php-fpm
    layer: backend
spec:
  type: ClusterIP
  selector:
    app: php-fpm
  ports:
    - port: 9000
      targetPort: 9000
